backend:
  name: github
  repo: ByMed-Medical/RamaisMedradius  # ← MUDE ESSA LINHA
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "ramais"
    label: "Ramais"
    files:
      - label: "Lista de Ramais"
        name: "ramais"
        file: "ramais.json"
        format: "json"
        fields:
          - label: "Entradas"
            name: "ramais"
            widget: "list"
            fields:
              - {label: "Ramal", name: "ramal", widget: "string"}
              - {label: "Local", name: "local", widget: "string"}
              - {label: "Setor", name: "setor", widget: "string"}
              - {label: "Subsetor", name: "subsetor", widget: "string"}
              - {label: "Workstation", name: "Workstation", widget: "string"}
              - {label: "Colaborador", name: "colaborador", widget: "string"}
